// <auto-generated>Generated by tools/gen-strings.ps1 from Strings.txt. Do not edit.</auto-generated>
#nullable enable
namespace WinPaint.App.Resources;

/// <summary>Localizable user-facing strings (backed by Strings.resx).</summary>
public static class Strings
{
    /// <summary>Resource manager for Strings.resx.</summary>
    public static System.Resources.ResourceManager ResourceManager { get; } = new("WinPaint.App.Resources.Strings", typeof(Strings).Assembly);

    /// <summary>Culture override (null = current UI culture).</summary>
    public static System.Globalization.CultureInfo? Culture { get; set; }

    /// <summary>Resource string AppName.</summary>
    public static string AppName => ResourceManager.GetString("AppName", Culture) ?? "AppName";

    /// <summary>Resource string Blend_Darken.</summary>
    public static string Blend_Darken => ResourceManager.GetString("Blend_Darken", Culture) ?? "Blend_Darken";

    /// <summary>Resource string Blend_Difference.</summary>
    public static string Blend_Difference => ResourceManager.GetString("Blend_Difference", Culture) ?? "Blend_Difference";

    /// <summary>Resource string Blend_Lighten.</summary>
    public static string Blend_Lighten => ResourceManager.GetString("Blend_Lighten", Culture) ?? "Blend_Lighten";

    /// <summary>Resource string Blend_Multiply.</summary>
    public static string Blend_Multiply => ResourceManager.GetString("Blend_Multiply", Culture) ?? "Blend_Multiply";

    /// <summary>Resource string Blend_Normal.</summary>
    public static string Blend_Normal => ResourceManager.GetString("Blend_Normal", Culture) ?? "Blend_Normal";

    /// <summary>Resource string Blend_Overlay.</summary>
    public static string Blend_Overlay => ResourceManager.GetString("Blend_Overlay", Culture) ?? "Blend_Overlay";

    /// <summary>Resource string Blend_Screen.</summary>
    public static string Blend_Screen => ResourceManager.GetString("Blend_Screen", Culture) ?? "Blend_Screen";

    /// <summary>Resource string Brush_Airbrush.</summary>
    public static string Brush_Airbrush => ResourceManager.GetString("Brush_Airbrush", Culture) ?? "Brush_Airbrush";

    /// <summary>Resource string Brush_Brush.</summary>
    public static string Brush_Brush => ResourceManager.GetString("Brush_Brush", Culture) ?? "Brush_Brush";

    /// <summary>Resource string Brush_CalligraphyBrush.</summary>
    public static string Brush_CalligraphyBrush => ResourceManager.GetString("Brush_CalligraphyBrush", Culture) ?? "Brush_CalligraphyBrush";

    /// <summary>Resource string Brush_CalligraphyPen.</summary>
    public static string Brush_CalligraphyPen => ResourceManager.GetString("Brush_CalligraphyPen", Culture) ?? "Brush_CalligraphyPen";

    /// <summary>Resource string Brush_Crayon.</summary>
    public static string Brush_Crayon => ResourceManager.GetString("Brush_Crayon", Culture) ?? "Brush_Crayon";

    /// <summary>Resource string Brush_Marker.</summary>
    public static string Brush_Marker => ResourceManager.GetString("Brush_Marker", Culture) ?? "Brush_Marker";

    /// <summary>Resource string Brush_NaturalPencil.</summary>
    public static string Brush_NaturalPencil => ResourceManager.GetString("Brush_NaturalPencil", Culture) ?? "Brush_NaturalPencil";

    /// <summary>Resource string Brush_Oil.</summary>
    public static string Brush_Oil => ResourceManager.GetString("Brush_Oil", Culture) ?? "Brush_Oil";

    /// <summary>Resource string Brush_Watercolor.</summary>
    public static string Brush_Watercolor => ResourceManager.GetString("Brush_Watercolor", Culture) ?? "Brush_Watercolor";

    /// <summary>Resource string Cancel.</summary>
    public static string Cancel => ResourceManager.GetString("Cancel", Culture) ?? "Cancel";

    /// <summary>Resource string Close.</summary>
    public static string Close => ResourceManager.GetString("Close", Culture) ?? "Close";

    /// <summary>Resource string Color_AddCustom.</summary>
    public static string Color_AddCustom => ResourceManager.GetString("Color_AddCustom", Culture) ?? "Color_AddCustom";

    /// <summary>Resource string Color_Color1.</summary>
    public static string Color_Color1 => ResourceManager.GetString("Color_Color1", Culture) ?? "Color_Color1";

    /// <summary>Resource string Color_Color2.</summary>
    public static string Color_Color2 => ResourceManager.GetString("Color_Color2", Culture) ?? "Color_Color2";

    /// <summary>Resource string Color_Custom.</summary>
    public static string Color_Custom => ResourceManager.GetString("Color_Custom", Culture) ?? "Color_Custom";

    /// <summary>Resource string Color_Edit.</summary>
    public static string Color_Edit => ResourceManager.GetString("Color_Edit", Culture) ?? "Color_Edit";

    /// <summary>Resource string Color_Palette.</summary>
    public static string Color_Palette => ResourceManager.GetString("Color_Palette", Culture) ?? "Color_Palette";

    /// <summary>Resource string Color_Swap.</summary>
    public static string Color_Swap => ResourceManager.GetString("Color_Swap", Culture) ?? "Color_Swap";

    /// <summary>Resource string DirtyPrefix.</summary>
    public static string DirtyPrefix => ResourceManager.GetString("DirtyPrefix", Culture) ?? "DirtyPrefix";

    /// <summary>Resource string Dlg_About.</summary>
    public static string Dlg_About => ResourceManager.GetString("Dlg_About", Culture) ?? "Dlg_About";

    /// <summary>Resource string Dlg_AboutText.</summary>
    public static string Dlg_AboutText => ResourceManager.GetString("Dlg_AboutText", Culture) ?? "Dlg_AboutText";

    /// <summary>Resource string Dlg_Action.</summary>
    public static string Dlg_Action => ResourceManager.GetString("Dlg_Action", Culture) ?? "Dlg_Action";

    /// <summary>Resource string Dlg_AdjustTo.</summary>
    public static string Dlg_AdjustTo => ResourceManager.GetString("Dlg_AdjustTo", Culture) ?? "Dlg_AdjustTo";

    /// <summary>Resource string Dlg_Alpha.</summary>
    public static string Dlg_Alpha => ResourceManager.GetString("Dlg_Alpha", Culture) ?? "Dlg_Alpha";

    /// <summary>Resource string Dlg_Attributes.</summary>
    public static string Dlg_Attributes => ResourceManager.GetString("Dlg_Attributes", Culture) ?? "Dlg_Attributes";

    /// <summary>Resource string Dlg_BlackWhite.</summary>
    public static string Dlg_BlackWhite => ResourceManager.GetString("Dlg_BlackWhite", Culture) ?? "Dlg_BlackWhite";

    /// <summary>Resource string Dlg_Blue.</summary>
    public static string Dlg_Blue => ResourceManager.GetString("Dlg_Blue", Culture) ?? "Dlg_Blue";

    /// <summary>Resource string Dlg_Bottom.</summary>
    public static string Dlg_Bottom => ResourceManager.GetString("Dlg_Bottom", Culture) ?? "Dlg_Bottom";

    /// <summary>Resource string Dlg_ByPercent.</summary>
    public static string Dlg_ByPercent => ResourceManager.GetString("Dlg_ByPercent", Culture) ?? "Dlg_ByPercent";

    /// <summary>Resource string Dlg_ByPixels.</summary>
    public static string Dlg_ByPixels => ResourceManager.GetString("Dlg_ByPixels", Culture) ?? "Dlg_ByPixels";

    /// <summary>Resource string Dlg_CenterH.</summary>
    public static string Dlg_CenterH => ResourceManager.GetString("Dlg_CenterH", Culture) ?? "Dlg_CenterH";

    /// <summary>Resource string Dlg_Centering.</summary>
    public static string Dlg_Centering => ResourceManager.GetString("Dlg_Centering", Culture) ?? "Dlg_Centering";

    /// <summary>Resource string Dlg_CenterV.</summary>
    public static string Dlg_CenterV => ResourceManager.GetString("Dlg_CenterV", Culture) ?? "Dlg_CenterV";

    /// <summary>Resource string Dlg_Centimeters.</summary>
    public static string Dlg_Centimeters => ResourceManager.GetString("Dlg_Centimeters", Culture) ?? "Dlg_Centimeters";

    /// <summary>Resource string Dlg_Color.</summary>
    public static string Dlg_Color => ResourceManager.GetString("Dlg_Color", Culture) ?? "Dlg_Color";

    /// <summary>Resource string Dlg_Colors.</summary>
    public static string Dlg_Colors => ResourceManager.GetString("Dlg_Colors", Culture) ?? "Dlg_Colors";

    /// <summary>Resource string Dlg_Default.</summary>
    public static string Dlg_Default => ResourceManager.GetString("Dlg_Default", Culture) ?? "Dlg_Default";

    /// <summary>Resource string Dlg_DotNet.</summary>
    public static string Dlg_DotNet => ResourceManager.GetString("Dlg_DotNet", Culture) ?? "Dlg_DotNet";

    /// <summary>Resource string Dlg_DpiFormat.</summary>
    public static string Dlg_DpiFormat => ResourceManager.GetString("Dlg_DpiFormat", Culture) ?? "Dlg_DpiFormat";

    /// <summary>Resource string Dlg_EditColors.</summary>
    public static string Dlg_EditColors => ResourceManager.GetString("Dlg_EditColors", Culture) ?? "Dlg_EditColors";

    /// <summary>Resource string Dlg_FitTo.</summary>
    public static string Dlg_FitTo => ResourceManager.GetString("Dlg_FitTo", Culture) ?? "Dlg_FitTo";

    /// <summary>Resource string Dlg_Green.</summary>
    public static string Dlg_Green => ResourceManager.GetString("Dlg_Green", Culture) ?? "Dlg_Green";

    /// <summary>Resource string Dlg_Height.</summary>
    public static string Dlg_Height => ResourceManager.GetString("Dlg_Height", Culture) ?? "Dlg_Height";

    /// <summary>Resource string Dlg_Hex.</summary>
    public static string Dlg_Hex => ResourceManager.GetString("Dlg_Hex", Culture) ?? "Dlg_Hex";

    /// <summary>Resource string Dlg_Horizontal.</summary>
    public static string Dlg_Horizontal => ResourceManager.GetString("Dlg_Horizontal", Culture) ?? "Dlg_Horizontal";

    /// <summary>Resource string Dlg_Hue.</summary>
    public static string Dlg_Hue => ResourceManager.GetString("Dlg_Hue", Culture) ?? "Dlg_Hue";

    /// <summary>Resource string Dlg_IcoSizes.</summary>
    public static string Dlg_IcoSizes => ResourceManager.GetString("Dlg_IcoSizes", Culture) ?? "Dlg_IcoSizes";

    /// <summary>Resource string Dlg_IcoSizesPrompt.</summary>
    public static string Dlg_IcoSizesPrompt => ResourceManager.GetString("Dlg_IcoSizesPrompt", Culture) ?? "Dlg_IcoSizesPrompt";

    /// <summary>Resource string Dlg_ImageProperties.</summary>
    public static string Dlg_ImageProperties => ResourceManager.GetString("Dlg_ImageProperties", Culture) ?? "Dlg_ImageProperties";

    /// <summary>Resource string Dlg_Inches.</summary>
    public static string Dlg_Inches => ResourceManager.GetString("Dlg_Inches", Culture) ?? "Dlg_Inches";

    /// <summary>Resource string Dlg_KeepAspect.</summary>
    public static string Dlg_KeepAspect => ResourceManager.GetString("Dlg_KeepAspect", Culture) ?? "Dlg_KeepAspect";

    /// <summary>Resource string Dlg_Landscape.</summary>
    public static string Dlg_Landscape => ResourceManager.GetString("Dlg_Landscape", Culture) ?? "Dlg_Landscape";

    /// <summary>Resource string Dlg_LastSaved.</summary>
    public static string Dlg_LastSaved => ResourceManager.GetString("Dlg_LastSaved", Culture) ?? "Dlg_LastSaved";

    /// <summary>Resource string Dlg_Left.</summary>
    public static string Dlg_Left => ResourceManager.GetString("Dlg_Left", Culture) ?? "Dlg_Left";

    /// <summary>Resource string Dlg_Margins.</summary>
    public static string Dlg_Margins => ResourceManager.GetString("Dlg_Margins", Culture) ?? "Dlg_Margins";

    /// <summary>Resource string Dlg_New.</summary>
    public static string Dlg_New => ResourceManager.GetString("Dlg_New", Culture) ?? "Dlg_New";

    /// <summary>Resource string Dlg_NewHeight.</summary>
    public static string Dlg_NewHeight => ResourceManager.GetString("Dlg_NewHeight", Culture) ?? "Dlg_NewHeight";

    /// <summary>Resource string Dlg_NewWidth.</summary>
    public static string Dlg_NewWidth => ResourceManager.GetString("Dlg_NewWidth", Culture) ?? "Dlg_NewWidth";

    /// <summary>Resource string Dlg_Next.</summary>
    public static string Dlg_Next => ResourceManager.GetString("Dlg_Next", Culture) ?? "Dlg_Next";

    /// <summary>Resource string Dlg_NormalSize.</summary>
    public static string Dlg_NormalSize => ResourceManager.GetString("Dlg_NormalSize", Culture) ?? "Dlg_NormalSize";

    /// <summary>Resource string Dlg_NotAvailable.</summary>
    public static string Dlg_NotAvailable => ResourceManager.GetString("Dlg_NotAvailable", Culture) ?? "Dlg_NotAvailable";

    /// <summary>Resource string Dlg_Old.</summary>
    public static string Dlg_Old => ResourceManager.GetString("Dlg_Old", Culture) ?? "Dlg_Old";

    /// <summary>Resource string Dlg_Orientation.</summary>
    public static string Dlg_Orientation => ResourceManager.GetString("Dlg_Orientation", Culture) ?? "Dlg_Orientation";

    /// <summary>Resource string Dlg_PageOf.</summary>
    public static string Dlg_PageOf => ResourceManager.GetString("Dlg_PageOf", Culture) ?? "Dlg_PageOf";

    /// <summary>Resource string Dlg_PageSetup.</summary>
    public static string Dlg_PageSetup => ResourceManager.GetString("Dlg_PageSetup", Culture) ?? "Dlg_PageSetup";

    /// <summary>Resource string Dlg_PagesTall.</summary>
    public static string Dlg_PagesTall => ResourceManager.GetString("Dlg_PagesTall", Culture) ?? "Dlg_PagesTall";

    /// <summary>Resource string Dlg_PagesWideBy.</summary>
    public static string Dlg_PagesWideBy => ResourceManager.GetString("Dlg_PagesWideBy", Culture) ?? "Dlg_PagesWideBy";

    /// <summary>Resource string Dlg_Pixels.</summary>
    public static string Dlg_Pixels => ResourceManager.GetString("Dlg_Pixels", Culture) ?? "Dlg_Pixels";

    /// <summary>Resource string Dlg_Portrait.</summary>
    public static string Dlg_Portrait => ResourceManager.GetString("Dlg_Portrait", Culture) ?? "Dlg_Portrait";

    /// <summary>Resource string Dlg_Previous.</summary>
    public static string Dlg_Previous => ResourceManager.GetString("Dlg_Previous", Culture) ?? "Dlg_Previous";

    /// <summary>Resource string Dlg_PrintButton.</summary>
    public static string Dlg_PrintButton => ResourceManager.GetString("Dlg_PrintButton", Culture) ?? "Dlg_PrintButton";

    /// <summary>Resource string Dlg_PrintPreview.</summary>
    public static string Dlg_PrintPreview => ResourceManager.GetString("Dlg_PrintPreview", Culture) ?? "Dlg_PrintPreview";

    /// <summary>Resource string Dlg_Red.</summary>
    public static string Dlg_Red => ResourceManager.GetString("Dlg_Red", Culture) ?? "Dlg_Red";

    /// <summary>Resource string Dlg_Resize.</summary>
    public static string Dlg_Resize => ResourceManager.GetString("Dlg_Resize", Culture) ?? "Dlg_Resize";

    /// <summary>Resource string Dlg_ResizeSkew.</summary>
    public static string Dlg_ResizeSkew => ResourceManager.GetString("Dlg_ResizeSkew", Culture) ?? "Dlg_ResizeSkew";

    /// <summary>Resource string Dlg_Resolution.</summary>
    public static string Dlg_Resolution => ResourceManager.GetString("Dlg_Resolution", Culture) ?? "Dlg_Resolution";

    /// <summary>Resource string Dlg_Right.</summary>
    public static string Dlg_Right => ResourceManager.GetString("Dlg_Right", Culture) ?? "Dlg_Right";

    /// <summary>Resource string Dlg_Sat.</summary>
    public static string Dlg_Sat => ResourceManager.GetString("Dlg_Sat", Culture) ?? "Dlg_Sat";

    /// <summary>Resource string Dlg_Scaling.</summary>
    public static string Dlg_Scaling => ResourceManager.GetString("Dlg_Scaling", Culture) ?? "Dlg_Scaling";

    /// <summary>Resource string Dlg_SettingsTitle.</summary>
    public static string Dlg_SettingsTitle => ResourceManager.GetString("Dlg_SettingsTitle", Culture) ?? "Dlg_SettingsTitle";

    /// <summary>Resource string Dlg_Shortcut.</summary>
    public static string Dlg_Shortcut => ResourceManager.GetString("Dlg_Shortcut", Culture) ?? "Dlg_Shortcut";

    /// <summary>Resource string Dlg_Shortcuts.</summary>
    public static string Dlg_Shortcuts => ResourceManager.GetString("Dlg_Shortcuts", Culture) ?? "Dlg_Shortcuts";

    /// <summary>Resource string Dlg_SizeOnDisk.</summary>
    public static string Dlg_SizeOnDisk => ResourceManager.GetString("Dlg_SizeOnDisk", Culture) ?? "Dlg_SizeOnDisk";

    /// <summary>Resource string Dlg_Skew.</summary>
    public static string Dlg_Skew => ResourceManager.GetString("Dlg_Skew", Culture) ?? "Dlg_Skew";

    /// <summary>Resource string Dlg_Theme.</summary>
    public static string Dlg_Theme => ResourceManager.GetString("Dlg_Theme", Culture) ?? "Dlg_Theme";

    /// <summary>Resource string Dlg_Thumbnail.</summary>
    public static string Dlg_Thumbnail => ResourceManager.GetString("Dlg_Thumbnail", Culture) ?? "Dlg_Thumbnail";

    /// <summary>Resource string Dlg_Top.</summary>
    public static string Dlg_Top => ResourceManager.GetString("Dlg_Top", Culture) ?? "Dlg_Top";

    /// <summary>Resource string Dlg_UndoBudget.</summary>
    public static string Dlg_UndoBudget => ResourceManager.GetString("Dlg_UndoBudget", Culture) ?? "Dlg_UndoBudget";

    /// <summary>Resource string Dlg_Units.</summary>
    public static string Dlg_Units => ResourceManager.GetString("Dlg_Units", Culture) ?? "Dlg_Units";

    /// <summary>Resource string Dlg_Val.</summary>
    public static string Dlg_Val => ResourceManager.GetString("Dlg_Val", Culture) ?? "Dlg_Val";

    /// <summary>Resource string Dlg_Version.</summary>
    public static string Dlg_Version => ResourceManager.GetString("Dlg_Version", Culture) ?? "Dlg_Version";

    /// <summary>Resource string Dlg_Vertical.</summary>
    public static string Dlg_Vertical => ResourceManager.GetString("Dlg_Vertical", Culture) ?? "Dlg_Vertical";

    /// <summary>Resource string Dlg_Width.</summary>
    public static string Dlg_Width => ResourceManager.GetString("Dlg_Width", Culture) ?? "Dlg_Width";

    /// <summary>Resource string Edit_Copy.</summary>
    public static string Edit_Copy => ResourceManager.GetString("Edit_Copy", Culture) ?? "Edit_Copy";

    /// <summary>Resource string Edit_Crop.</summary>
    public static string Edit_Crop => ResourceManager.GetString("Edit_Crop", Culture) ?? "Edit_Crop";

    /// <summary>Resource string Edit_Cut.</summary>
    public static string Edit_Cut => ResourceManager.GetString("Edit_Cut", Culture) ?? "Edit_Cut";

    /// <summary>Resource string Edit_Delete.</summary>
    public static string Edit_Delete => ResourceManager.GetString("Edit_Delete", Culture) ?? "Edit_Delete";

    /// <summary>Resource string Edit_InvertColors.</summary>
    public static string Edit_InvertColors => ResourceManager.GetString("Edit_InvertColors", Culture) ?? "Edit_InvertColors";

    /// <summary>Resource string Edit_InvertSelection.</summary>
    public static string Edit_InvertSelection => ResourceManager.GetString("Edit_InvertSelection", Culture) ?? "Edit_InvertSelection";

    /// <summary>Resource string Edit_Paste.</summary>
    public static string Edit_Paste => ResourceManager.GetString("Edit_Paste", Culture) ?? "Edit_Paste";

    /// <summary>Resource string Edit_PasteFrom.</summary>
    public static string Edit_PasteFrom => ResourceManager.GetString("Edit_PasteFrom", Culture) ?? "Edit_PasteFrom";

    /// <summary>Resource string Edit_Redo.</summary>
    public static string Edit_Redo => ResourceManager.GetString("Edit_Redo", Culture) ?? "Edit_Redo";

    /// <summary>Resource string Edit_SelectAll.</summary>
    public static string Edit_SelectAll => ResourceManager.GetString("Edit_SelectAll", Culture) ?? "Edit_SelectAll";

    /// <summary>Resource string Edit_Undo.</summary>
    public static string Edit_Undo => ResourceManager.GetString("Edit_Undo", Culture) ?? "Edit_Undo";

    /// <summary>Resource string File_ClearRecent.</summary>
    public static string File_ClearRecent => ResourceManager.GetString("File_ClearRecent", Culture) ?? "File_ClearRecent";

    /// <summary>Resource string File_Exit.</summary>
    public static string File_Exit => ResourceManager.GetString("File_Exit", Culture) ?? "File_Exit";

    /// <summary>Resource string File_Import.</summary>
    public static string File_Import => ResourceManager.GetString("File_Import", Culture) ?? "File_Import";

    /// <summary>Resource string File_ImportFromFile.</summary>
    public static string File_ImportFromFile => ResourceManager.GetString("File_ImportFromFile", Culture) ?? "File_ImportFromFile";

    /// <summary>Resource string File_New.</summary>
    public static string File_New => ResourceManager.GetString("File_New", Culture) ?? "File_New";

    /// <summary>Resource string File_NoRecent.</summary>
    public static string File_NoRecent => ResourceManager.GetString("File_NoRecent", Culture) ?? "File_NoRecent";

    /// <summary>Resource string File_Open.</summary>
    public static string File_Open => ResourceManager.GetString("File_Open", Culture) ?? "File_Open";

    /// <summary>Resource string File_PageSetup.</summary>
    public static string File_PageSetup => ResourceManager.GetString("File_PageSetup", Culture) ?? "File_PageSetup";

    /// <summary>Resource string File_Print.</summary>
    public static string File_Print => ResourceManager.GetString("File_Print", Culture) ?? "File_Print";

    /// <summary>Resource string File_PrintDots.</summary>
    public static string File_PrintDots => ResourceManager.GetString("File_PrintDots", Culture) ?? "File_PrintDots";

    /// <summary>Resource string File_PrintPreview.</summary>
    public static string File_PrintPreview => ResourceManager.GetString("File_PrintPreview", Culture) ?? "File_PrintPreview";

    /// <summary>Resource string File_Properties.</summary>
    public static string File_Properties => ResourceManager.GetString("File_Properties", Culture) ?? "File_Properties";

    /// <summary>Resource string File_Recent.</summary>
    public static string File_Recent => ResourceManager.GetString("File_Recent", Culture) ?? "File_Recent";

    /// <summary>Resource string File_Save.</summary>
    public static string File_Save => ResourceManager.GetString("File_Save", Culture) ?? "File_Save";

    /// <summary>Resource string File_SaveAs.</summary>
    public static string File_SaveAs => ResourceManager.GetString("File_SaveAs", Culture) ?? "File_SaveAs";

    /// <summary>Resource string File_SetCenter.</summary>
    public static string File_SetCenter => ResourceManager.GetString("File_SetCenter", Culture) ?? "File_SetCenter";

    /// <summary>Resource string File_SetDesktop.</summary>
    public static string File_SetDesktop => ResourceManager.GetString("File_SetDesktop", Culture) ?? "File_SetDesktop";

    /// <summary>Resource string File_SetFill.</summary>
    public static string File_SetFill => ResourceManager.GetString("File_SetFill", Culture) ?? "File_SetFill";

    /// <summary>Resource string File_SetTile.</summary>
    public static string File_SetTile => ResourceManager.GetString("File_SetTile", Culture) ?? "File_SetTile";

    /// <summary>Resource string Group_Brushes.</summary>
    public static string Group_Brushes => ResourceManager.GetString("Group_Brushes", Culture) ?? "Group_Brushes";

    /// <summary>Resource string Group_Colors.</summary>
    public static string Group_Colors => ResourceManager.GetString("Group_Colors", Culture) ?? "Group_Colors";

    /// <summary>Resource string Group_Image.</summary>
    public static string Group_Image => ResourceManager.GetString("Group_Image", Culture) ?? "Group_Image";

    /// <summary>Resource string Group_Layers.</summary>
    public static string Group_Layers => ResourceManager.GetString("Group_Layers", Culture) ?? "Group_Layers";

    /// <summary>Resource string Group_Selection.</summary>
    public static string Group_Selection => ResourceManager.GetString("Group_Selection", Culture) ?? "Group_Selection";

    /// <summary>Resource string Group_Shapes.</summary>
    public static string Group_Shapes => ResourceManager.GetString("Group_Shapes", Culture) ?? "Group_Shapes";

    /// <summary>Resource string Group_Size.</summary>
    public static string Group_Size => ResourceManager.GetString("Group_Size", Culture) ?? "Group_Size";

    /// <summary>Resource string Group_Tools.</summary>
    public static string Group_Tools => ResourceManager.GetString("Group_Tools", Culture) ?? "Group_Tools";

    /// <summary>Resource string Help_About.</summary>
    public static string Help_About => ResourceManager.GetString("Help_About", Culture) ?? "Help_About";

    /// <summary>Resource string Help_Shortcuts.</summary>
    public static string Help_Shortcuts => ResourceManager.GetString("Help_Shortcuts", Culture) ?? "Help_Shortcuts";

    /// <summary>Resource string Img_Crop.</summary>
    public static string Img_Crop => ResourceManager.GetString("Img_Crop", Culture) ?? "Img_Crop";

    /// <summary>Resource string Img_FlipHorizontal.</summary>
    public static string Img_FlipHorizontal => ResourceManager.GetString("Img_FlipHorizontal", Culture) ?? "Img_FlipHorizontal";

    /// <summary>Resource string Img_FlipVertical.</summary>
    public static string Img_FlipVertical => ResourceManager.GetString("Img_FlipVertical", Culture) ?? "Img_FlipVertical";

    /// <summary>Resource string Img_InvertColors.</summary>
    public static string Img_InvertColors => ResourceManager.GetString("Img_InvertColors", Culture) ?? "Img_InvertColors";

    /// <summary>Resource string Img_Resize.</summary>
    public static string Img_Resize => ResourceManager.GetString("Img_Resize", Culture) ?? "Img_Resize";

    /// <summary>Resource string Img_Rotate.</summary>
    public static string Img_Rotate => ResourceManager.GetString("Img_Rotate", Culture) ?? "Img_Rotate";

    /// <summary>Resource string Img_Rotate180.</summary>
    public static string Img_Rotate180 => ResourceManager.GetString("Img_Rotate180", Culture) ?? "Img_Rotate180";

    /// <summary>Resource string Img_RotateLeft.</summary>
    public static string Img_RotateLeft => ResourceManager.GetString("Img_RotateLeft", Culture) ?? "Img_RotateLeft";

    /// <summary>Resource string Img_RotateRight.</summary>
    public static string Img_RotateRight => ResourceManager.GetString("Img_RotateRight", Culture) ?? "Img_RotateRight";

    /// <summary>Resource string Img_TransparentCanvas.</summary>
    public static string Img_TransparentCanvas => ResourceManager.GetString("Img_TransparentCanvas", Culture) ?? "Img_TransparentCanvas";

    /// <summary>Resource string Layer_Add.</summary>
    public static string Layer_Add => ResourceManager.GetString("Layer_Add", Culture) ?? "Layer_Add";

    /// <summary>Resource string Layer_Background.</summary>
    public static string Layer_Background => ResourceManager.GetString("Layer_Background", Culture) ?? "Layer_Background";

    /// <summary>Resource string Layer_BlendMode.</summary>
    public static string Layer_BlendMode => ResourceManager.GetString("Layer_BlendMode", Culture) ?? "Layer_BlendMode";

    /// <summary>Resource string Layer_CannotDeleteLast.</summary>
    public static string Layer_CannotDeleteLast => ResourceManager.GetString("Layer_CannotDeleteLast", Culture) ?? "Layer_CannotDeleteLast";

    /// <summary>Resource string Layer_Delete.</summary>
    public static string Layer_Delete => ResourceManager.GetString("Layer_Delete", Culture) ?? "Layer_Delete";

    /// <summary>Resource string Layer_Duplicate.</summary>
    public static string Layer_Duplicate => ResourceManager.GetString("Layer_Duplicate", Culture) ?? "Layer_Duplicate";

    /// <summary>Resource string Layer_Flatten.</summary>
    public static string Layer_Flatten => ResourceManager.GetString("Layer_Flatten", Culture) ?? "Layer_Flatten";

    /// <summary>Resource string Layer_FlattenConfirm.</summary>
    public static string Layer_FlattenConfirm => ResourceManager.GetString("Layer_FlattenConfirm", Culture) ?? "Layer_FlattenConfirm";

    /// <summary>Resource string Layer_MergeDown.</summary>
    public static string Layer_MergeDown => ResourceManager.GetString("Layer_MergeDown", Culture) ?? "Layer_MergeDown";

    /// <summary>Resource string Layer_MoveDown.</summary>
    public static string Layer_MoveDown => ResourceManager.GetString("Layer_MoveDown", Culture) ?? "Layer_MoveDown";

    /// <summary>Resource string Layer_MoveUp.</summary>
    public static string Layer_MoveUp => ResourceManager.GetString("Layer_MoveUp", Culture) ?? "Layer_MoveUp";

    /// <summary>Resource string Layer_Name.</summary>
    public static string Layer_Name => ResourceManager.GetString("Layer_Name", Culture) ?? "Layer_Name";

    /// <summary>Resource string Layer_Opacity.</summary>
    public static string Layer_Opacity => ResourceManager.GetString("Layer_Opacity", Culture) ?? "Layer_Opacity";

    /// <summary>Resource string Layer_Panel.</summary>
    public static string Layer_Panel => ResourceManager.GetString("Layer_Panel", Culture) ?? "Layer_Panel";

    /// <summary>Resource string Layer_Visibility.</summary>
    public static string Layer_Visibility => ResourceManager.GetString("Layer_Visibility", Culture) ?? "Layer_Visibility";

    /// <summary>Resource string Menu_Edit.</summary>
    public static string Menu_Edit => ResourceManager.GetString("Menu_Edit", Culture) ?? "Menu_Edit";

    /// <summary>Resource string Menu_File.</summary>
    public static string Menu_File => ResourceManager.GetString("Menu_File", Culture) ?? "Menu_File";

    /// <summary>Resource string Menu_Help.</summary>
    public static string Menu_Help => ResourceManager.GetString("Menu_Help", Culture) ?? "Menu_Help";

    /// <summary>Resource string Menu_View.</summary>
    public static string Menu_View => ResourceManager.GetString("Menu_View", Culture) ?? "Menu_View";

    /// <summary>Resource string Msg_BlackWhiteConfirm.</summary>
    public static string Msg_BlackWhiteConfirm => ResourceManager.GetString("Msg_BlackWhiteConfirm", Culture) ?? "Msg_BlackWhiteConfirm";

    /// <summary>Resource string Msg_Crash.</summary>
    public static string Msg_Crash => ResourceManager.GetString("Msg_Crash", Culture) ?? "Msg_Crash";

    /// <summary>Resource string Msg_CrashTitle.</summary>
    public static string Msg_CrashTitle => ResourceManager.GetString("Msg_CrashTitle", Culture) ?? "Msg_CrashTitle";

    /// <summary>Resource string Msg_GifQuality.</summary>
    public static string Msg_GifQuality => ResourceManager.GetString("Msg_GifQuality", Culture) ?? "Msg_GifQuality";

    /// <summary>Resource string Msg_IcoNotSquare.</summary>
    public static string Msg_IcoNotSquare => ResourceManager.GetString("Msg_IcoNotSquare", Culture) ?? "Msg_IcoNotSquare";

    /// <summary>Resource string Msg_ImageTooLarge.</summary>
    public static string Msg_ImageTooLarge => ResourceManager.GetString("Msg_ImageTooLarge", Culture) ?? "Msg_ImageTooLarge";

    /// <summary>Resource string Msg_JpegTransparency.</summary>
    public static string Msg_JpegTransparency => ResourceManager.GetString("Msg_JpegTransparency", Culture) ?? "Msg_JpegTransparency";

    /// <summary>Resource string Msg_MustSaveForWallpaper.</summary>
    public static string Msg_MustSaveForWallpaper => ResourceManager.GetString("Msg_MustSaveForWallpaper", Culture) ?? "Msg_MustSaveForWallpaper";

    /// <summary>Resource string Msg_NothingToPrint.</summary>
    public static string Msg_NothingToPrint => ResourceManager.GetString("Msg_NothingToPrint", Culture) ?? "Msg_NothingToPrint";

    /// <summary>Resource string Msg_OpenFailed.</summary>
    public static string Msg_OpenFailed => ResourceManager.GetString("Msg_OpenFailed", Culture) ?? "Msg_OpenFailed";

    /// <summary>Resource string Msg_PasteEnlarge.</summary>
    public static string Msg_PasteEnlarge => ResourceManager.GetString("Msg_PasteEnlarge", Culture) ?? "Msg_PasteEnlarge";

    /// <summary>Resource string Msg_PrintFailed.</summary>
    public static string Msg_PrintFailed => ResourceManager.GetString("Msg_PrintFailed", Culture) ?? "Msg_PrintFailed";

    /// <summary>Resource string Msg_RecentMissing.</summary>
    public static string Msg_RecentMissing => ResourceManager.GetString("Msg_RecentMissing", Culture) ?? "Msg_RecentMissing";

    /// <summary>Resource string Msg_RecoverySaved.</summary>
    public static string Msg_RecoverySaved => ResourceManager.GetString("Msg_RecoverySaved", Culture) ?? "Msg_RecoverySaved";

    /// <summary>Resource string Msg_SaveFailed.</summary>
    public static string Msg_SaveFailed => ResourceManager.GetString("Msg_SaveFailed", Culture) ?? "Msg_SaveFailed";

    /// <summary>Resource string Msg_WallpaperFailed.</summary>
    public static string Msg_WallpaperFailed => ResourceManager.GetString("Msg_WallpaperFailed", Culture) ?? "Msg_WallpaperFailed";

    /// <summary>Resource string No.</summary>
    public static string No => ResourceManager.GetString("No", Culture) ?? "No";

    /// <summary>Resource string OK.</summary>
    public static string OK => ResourceManager.GetString("OK", Culture) ?? "OK";

    /// <summary>Resource string Prompt_DontSave.</summary>
    public static string Prompt_DontSave => ResourceManager.GetString("Prompt_DontSave", Culture) ?? "Prompt_DontSave";

    /// <summary>Resource string Prompt_Save.</summary>
    public static string Prompt_Save => ResourceManager.GetString("Prompt_Save", Culture) ?? "Prompt_Save";

    /// <summary>Resource string Prompt_SaveChanges.</summary>
    public static string Prompt_SaveChanges => ResourceManager.GetString("Prompt_SaveChanges", Culture) ?? "Prompt_SaveChanges";

    /// <summary>Resource string Sc_Actual.</summary>
    public static string Sc_Actual => ResourceManager.GetString("Sc_Actual", Culture) ?? "Sc_Actual";

    /// <summary>Resource string Sc_Crop.</summary>
    public static string Sc_Crop => ResourceManager.GetString("Sc_Crop", Culture) ?? "Sc_Crop";

    /// <summary>Resource string Sc_CutCopyPaste.</summary>
    public static string Sc_CutCopyPaste => ResourceManager.GetString("Sc_CutCopyPaste", Culture) ?? "Sc_CutCopyPaste";

    /// <summary>Resource string Sc_Delete.</summary>
    public static string Sc_Delete => ResourceManager.GetString("Sc_Delete", Culture) ?? "Sc_Delete";

    /// <summary>Resource string Sc_Escape.</summary>
    public static string Sc_Escape => ResourceManager.GetString("Sc_Escape", Culture) ?? "Sc_Escape";

    /// <summary>Resource string Sc_Fit.</summary>
    public static string Sc_Fit => ResourceManager.GetString("Sc_Fit", Culture) ?? "Sc_Fit";

    /// <summary>Resource string Sc_FullScreen.</summary>
    public static string Sc_FullScreen => ResourceManager.GetString("Sc_FullScreen", Culture) ?? "Sc_FullScreen";

    /// <summary>Resource string Sc_Gridlines.</summary>
    public static string Sc_Gridlines => ResourceManager.GetString("Sc_Gridlines", Culture) ?? "Sc_Gridlines";

    /// <summary>Resource string Sc_Help.</summary>
    public static string Sc_Help => ResourceManager.GetString("Sc_Help", Culture) ?? "Sc_Help";

    /// <summary>Resource string Sc_Invert.</summary>
    public static string Sc_Invert => ResourceManager.GetString("Sc_Invert", Culture) ?? "Sc_Invert";

    /// <summary>Resource string Sc_New.</summary>
    public static string Sc_New => ResourceManager.GetString("Sc_New", Culture) ?? "Sc_New";

    /// <summary>Resource string Sc_NewLine.</summary>
    public static string Sc_NewLine => ResourceManager.GetString("Sc_NewLine", Culture) ?? "Sc_NewLine";

    /// <summary>Resource string Sc_Nudge.</summary>
    public static string Sc_Nudge => ResourceManager.GetString("Sc_Nudge", Culture) ?? "Sc_Nudge";

    /// <summary>Resource string Sc_Open.</summary>
    public static string Sc_Open => ResourceManager.GetString("Sc_Open", Culture) ?? "Sc_Open";

    /// <summary>Resource string Sc_Print.</summary>
    public static string Sc_Print => ResourceManager.GetString("Sc_Print", Culture) ?? "Sc_Print";

    /// <summary>Resource string Sc_Properties.</summary>
    public static string Sc_Properties => ResourceManager.GetString("Sc_Properties", Culture) ?? "Sc_Properties";

    /// <summary>Resource string Sc_Redo.</summary>
    public static string Sc_Redo => ResourceManager.GetString("Sc_Redo", Culture) ?? "Sc_Redo";

    /// <summary>Resource string Sc_ResizeSkew.</summary>
    public static string Sc_ResizeSkew => ResourceManager.GetString("Sc_ResizeSkew", Culture) ?? "Sc_ResizeSkew";

    /// <summary>Resource string Sc_Rulers.</summary>
    public static string Sc_Rulers => ResourceManager.GetString("Sc_Rulers", Culture) ?? "Sc_Rulers";

    /// <summary>Resource string Sc_Save.</summary>
    public static string Sc_Save => ResourceManager.GetString("Sc_Save", Culture) ?? "Sc_Save";

    /// <summary>Resource string Sc_SaveAs.</summary>
    public static string Sc_SaveAs => ResourceManager.GetString("Sc_SaveAs", Culture) ?? "Sc_SaveAs";

    /// <summary>Resource string Sc_SelectAll.</summary>
    public static string Sc_SelectAll => ResourceManager.GetString("Sc_SelectAll", Culture) ?? "Sc_SelectAll";

    /// <summary>Resource string Sc_SizeUpDown.</summary>
    public static string Sc_SizeUpDown => ResourceManager.GetString("Sc_SizeUpDown", Culture) ?? "Sc_SizeUpDown";

    /// <summary>Resource string Sc_Swap.</summary>
    public static string Sc_Swap => ResourceManager.GetString("Sc_Swap", Culture) ?? "Sc_Swap";

    /// <summary>Resource string Sc_TabNav.</summary>
    public static string Sc_TabNav => ResourceManager.GetString("Sc_TabNav", Culture) ?? "Sc_TabNav";

    /// <summary>Resource string Sc_TextFormat.</summary>
    public static string Sc_TextFormat => ResourceManager.GetString("Sc_TextFormat", Culture) ?? "Sc_TextFormat";

    /// <summary>Resource string Sc_Undo.</summary>
    public static string Sc_Undo => ResourceManager.GetString("Sc_Undo", Culture) ?? "Sc_Undo";

    /// <summary>Resource string Sc_ZoomInOut.</summary>
    public static string Sc_ZoomInOut => ResourceManager.GetString("Sc_ZoomInOut", Culture) ?? "Sc_ZoomInOut";

    /// <summary>Resource string Sc_ZoomWheel.</summary>
    public static string Sc_ZoomWheel => ResourceManager.GetString("Sc_ZoomWheel", Culture) ?? "Sc_ZoomWheel";

    /// <summary>Resource string Sel_Delete.</summary>
    public static string Sel_Delete => ResourceManager.GetString("Sel_Delete", Culture) ?? "Sel_Delete";

    /// <summary>Resource string Sel_FreeForm.</summary>
    public static string Sel_FreeForm => ResourceManager.GetString("Sel_FreeForm", Culture) ?? "Sel_FreeForm";

    /// <summary>Resource string Sel_Invert.</summary>
    public static string Sel_Invert => ResourceManager.GetString("Sel_Invert", Culture) ?? "Sel_Invert";

    /// <summary>Resource string Sel_Rectangle.</summary>
    public static string Sel_Rectangle => ResourceManager.GetString("Sel_Rectangle", Culture) ?? "Sel_Rectangle";

    /// <summary>Resource string Sel_SelectAll.</summary>
    public static string Sel_SelectAll => ResourceManager.GetString("Sel_SelectAll", Culture) ?? "Sel_SelectAll";

    /// <summary>Resource string Sel_Tip.</summary>
    public static string Sel_Tip => ResourceManager.GetString("Sel_Tip", Culture) ?? "Sel_Tip";

    /// <summary>Resource string Sel_Transparent.</summary>
    public static string Sel_Transparent => ResourceManager.GetString("Sel_Transparent", Culture) ?? "Sel_Transparent";

    /// <summary>Resource string Settings.</summary>
    public static string Settings => ResourceManager.GetString("Settings", Culture) ?? "Settings";

    /// <summary>Resource string Shape_CloudCallout.</summary>
    public static string Shape_CloudCallout => ResourceManager.GetString("Shape_CloudCallout", Culture) ?? "Shape_CloudCallout";

    /// <summary>Resource string Shape_Curve.</summary>
    public static string Shape_Curve => ResourceManager.GetString("Shape_Curve", Culture) ?? "Shape_Curve";

    /// <summary>Resource string Shape_Diamond.</summary>
    public static string Shape_Diamond => ResourceManager.GetString("Shape_Diamond", Culture) ?? "Shape_Diamond";

    /// <summary>Resource string Shape_DownArrow.</summary>
    public static string Shape_DownArrow => ResourceManager.GetString("Shape_DownArrow", Culture) ?? "Shape_DownArrow";

    /// <summary>Resource string Shape_Fill.</summary>
    public static string Shape_Fill => ResourceManager.GetString("Shape_Fill", Culture) ?? "Shape_Fill";

    /// <summary>Resource string Shape_FivePointStar.</summary>
    public static string Shape_FivePointStar => ResourceManager.GetString("Shape_FivePointStar", Culture) ?? "Shape_FivePointStar";

    /// <summary>Resource string Shape_FourPointStar.</summary>
    public static string Shape_FourPointStar => ResourceManager.GetString("Shape_FourPointStar", Culture) ?? "Shape_FourPointStar";

    /// <summary>Resource string Shape_Heart.</summary>
    public static string Shape_Heart => ResourceManager.GetString("Shape_Heart", Culture) ?? "Shape_Heart";

    /// <summary>Resource string Shape_Hexagon.</summary>
    public static string Shape_Hexagon => ResourceManager.GetString("Shape_Hexagon", Culture) ?? "Shape_Hexagon";

    /// <summary>Resource string Shape_LeftArrow.</summary>
    public static string Shape_LeftArrow => ResourceManager.GetString("Shape_LeftArrow", Culture) ?? "Shape_LeftArrow";

    /// <summary>Resource string Shape_Lightning.</summary>
    public static string Shape_Lightning => ResourceManager.GetString("Shape_Lightning", Culture) ?? "Shape_Lightning";

    /// <summary>Resource string Shape_Line.</summary>
    public static string Shape_Line => ResourceManager.GetString("Shape_Line", Culture) ?? "Shape_Line";

    /// <summary>Resource string Shape_Outline.</summary>
    public static string Shape_Outline => ResourceManager.GetString("Shape_Outline", Culture) ?? "Shape_Outline";

    /// <summary>Resource string Shape_Oval.</summary>
    public static string Shape_Oval => ResourceManager.GetString("Shape_Oval", Culture) ?? "Shape_Oval";

    /// <summary>Resource string Shape_OvalCallout.</summary>
    public static string Shape_OvalCallout => ResourceManager.GetString("Shape_OvalCallout", Culture) ?? "Shape_OvalCallout";

    /// <summary>Resource string Shape_Pentagon.</summary>
    public static string Shape_Pentagon => ResourceManager.GetString("Shape_Pentagon", Culture) ?? "Shape_Pentagon";

    /// <summary>Resource string Shape_Polygon.</summary>
    public static string Shape_Polygon => ResourceManager.GetString("Shape_Polygon", Culture) ?? "Shape_Polygon";

    /// <summary>Resource string Shape_Rectangle.</summary>
    public static string Shape_Rectangle => ResourceManager.GetString("Shape_Rectangle", Culture) ?? "Shape_Rectangle";

    /// <summary>Resource string Shape_RightArrow.</summary>
    public static string Shape_RightArrow => ResourceManager.GetString("Shape_RightArrow", Culture) ?? "Shape_RightArrow";

    /// <summary>Resource string Shape_RightTriangle.</summary>
    public static string Shape_RightTriangle => ResourceManager.GetString("Shape_RightTriangle", Culture) ?? "Shape_RightTriangle";

    /// <summary>Resource string Shape_RoundedRectangle.</summary>
    public static string Shape_RoundedRectangle => ResourceManager.GetString("Shape_RoundedRectangle", Culture) ?? "Shape_RoundedRectangle";

    /// <summary>Resource string Shape_RoundedRectCallout.</summary>
    public static string Shape_RoundedRectCallout => ResourceManager.GetString("Shape_RoundedRectCallout", Culture) ?? "Shape_RoundedRectCallout";

    /// <summary>Resource string Shape_SixPointStar.</summary>
    public static string Shape_SixPointStar => ResourceManager.GetString("Shape_SixPointStar", Culture) ?? "Shape_SixPointStar";

    /// <summary>Resource string Shape_Triangle.</summary>
    public static string Shape_Triangle => ResourceManager.GetString("Shape_Triangle", Culture) ?? "Shape_Triangle";

    /// <summary>Resource string Shape_UpArrow.</summary>
    public static string Shape_UpArrow => ResourceManager.GetString("Shape_UpArrow", Culture) ?? "Shape_UpArrow";

    /// <summary>Resource string Size_Opacity.</summary>
    public static string Size_Opacity => ResourceManager.GetString("Size_Opacity", Culture) ?? "Size_Opacity";

    /// <summary>Resource string Size_Px.</summary>
    public static string Size_Px => ResourceManager.GetString("Size_Px", Culture) ?? "Size_Px";

    /// <summary>Resource string Size_Size.</summary>
    public static string Size_Size => ResourceManager.GetString("Size_Size", Culture) ?? "Size_Size";

    /// <summary>Resource string Status_EditingText.</summary>
    public static string Status_EditingText => ResourceManager.GetString("Status_EditingText", Culture) ?? "Status_EditingText";

    /// <summary>Resource string Status_FileSize.</summary>
    public static string Status_FileSize => ResourceManager.GetString("Status_FileSize", Culture) ?? "Status_FileSize";

    /// <summary>Resource string Status_Fit.</summary>
    public static string Status_Fit => ResourceManager.GetString("Status_Fit", Culture) ?? "Status_Fit";

    /// <summary>Resource string Status_Position.</summary>
    public static string Status_Position => ResourceManager.GetString("Status_Position", Culture) ?? "Status_Position";

    /// <summary>Resource string Status_ResizePreview.</summary>
    public static string Status_ResizePreview => ResourceManager.GetString("Status_ResizePreview", Culture) ?? "Status_ResizePreview";

    /// <summary>Resource string Status_Size.</summary>
    public static string Status_Size => ResourceManager.GetString("Status_Size", Culture) ?? "Status_Size";

    /// <summary>Resource string Status_TextFlattened.</summary>
    public static string Status_TextFlattened => ResourceManager.GetString("Status_TextFlattened", Culture) ?? "Status_TextFlattened";

    /// <summary>Resource string Status_Zoom.</summary>
    public static string Status_Zoom => ResourceManager.GetString("Status_Zoom", Culture) ?? "Status_Zoom";

    /// <summary>Resource string Status_ZoomIn.</summary>
    public static string Status_ZoomIn => ResourceManager.GetString("Status_ZoomIn", Culture) ?? "Status_ZoomIn";

    /// <summary>Resource string Status_ZoomOut.</summary>
    public static string Status_ZoomOut => ResourceManager.GetString("Status_ZoomOut", Culture) ?? "Status_ZoomOut";

    /// <summary>Resource string Style_Crayon.</summary>
    public static string Style_Crayon => ResourceManager.GetString("Style_Crayon", Culture) ?? "Style_Crayon";

    /// <summary>Resource string Style_Marker.</summary>
    public static string Style_Marker => ResourceManager.GetString("Style_Marker", Culture) ?? "Style_Marker";

    /// <summary>Resource string Style_NaturalPencil.</summary>
    public static string Style_NaturalPencil => ResourceManager.GetString("Style_NaturalPencil", Culture) ?? "Style_NaturalPencil";

    /// <summary>Resource string Style_NoFill.</summary>
    public static string Style_NoFill => ResourceManager.GetString("Style_NoFill", Culture) ?? "Style_NoFill";

    /// <summary>Resource string Style_NoOutline.</summary>
    public static string Style_NoOutline => ResourceManager.GetString("Style_NoOutline", Culture) ?? "Style_NoOutline";

    /// <summary>Resource string Style_Oil.</summary>
    public static string Style_Oil => ResourceManager.GetString("Style_Oil", Culture) ?? "Style_Oil";

    /// <summary>Resource string Style_Solid.</summary>
    public static string Style_Solid => ResourceManager.GetString("Style_Solid", Culture) ?? "Style_Solid";

    /// <summary>Resource string Style_Watercolor.</summary>
    public static string Style_Watercolor => ResourceManager.GetString("Style_Watercolor", Culture) ?? "Style_Watercolor";

    /// <summary>Resource string Text_Background.</summary>
    public static string Text_Background => ResourceManager.GetString("Text_Background", Culture) ?? "Text_Background";

    /// <summary>Resource string Text_Bold.</summary>
    public static string Text_Bold => ResourceManager.GetString("Text_Bold", Culture) ?? "Text_Bold";

    /// <summary>Resource string Text_Color.</summary>
    public static string Text_Color => ResourceManager.GetString("Text_Color", Culture) ?? "Text_Color";

    /// <summary>Resource string Text_Delete.</summary>
    public static string Text_Delete => ResourceManager.GetString("Text_Delete", Culture) ?? "Text_Delete";

    /// <summary>Resource string Text_Font.</summary>
    public static string Text_Font => ResourceManager.GetString("Text_Font", Culture) ?? "Text_Font";

    /// <summary>Resource string Text_Italic.</summary>
    public static string Text_Italic => ResourceManager.GetString("Text_Italic", Culture) ?? "Text_Italic";

    /// <summary>Resource string Text_Opaque.</summary>
    public static string Text_Opaque => ResourceManager.GetString("Text_Opaque", Culture) ?? "Text_Opaque";

    /// <summary>Resource string Text_Size.</summary>
    public static string Text_Size => ResourceManager.GetString("Text_Size", Culture) ?? "Text_Size";

    /// <summary>Resource string Text_Strikethrough.</summary>
    public static string Text_Strikethrough => ResourceManager.GetString("Text_Strikethrough", Culture) ?? "Text_Strikethrough";

    /// <summary>Resource string Text_Transparent.</summary>
    public static string Text_Transparent => ResourceManager.GetString("Text_Transparent", Culture) ?? "Text_Transparent";

    /// <summary>Resource string Text_Underline.</summary>
    public static string Text_Underline => ResourceManager.GetString("Text_Underline", Culture) ?? "Text_Underline";

    /// <summary>Resource string Theme_Dark.</summary>
    public static string Theme_Dark => ResourceManager.GetString("Theme_Dark", Culture) ?? "Theme_Dark";

    /// <summary>Resource string Theme_Light.</summary>
    public static string Theme_Light => ResourceManager.GetString("Theme_Light", Culture) ?? "Theme_Light";

    /// <summary>Resource string Theme_System.</summary>
    public static string Theme_System => ResourceManager.GetString("Theme_System", Culture) ?? "Theme_System";

    /// <summary>Resource string TitleFormat.</summary>
    public static string TitleFormat => ResourceManager.GetString("TitleFormat", Culture) ?? "TitleFormat";

    /// <summary>Resource string Tool_Eraser.</summary>
    public static string Tool_Eraser => ResourceManager.GetString("Tool_Eraser", Culture) ?? "Tool_Eraser";

    /// <summary>Resource string Tool_Fill.</summary>
    public static string Tool_Fill => ResourceManager.GetString("Tool_Fill", Culture) ?? "Tool_Fill";

    /// <summary>Resource string Tool_Magnifier.</summary>
    public static string Tool_Magnifier => ResourceManager.GetString("Tool_Magnifier", Culture) ?? "Tool_Magnifier";

    /// <summary>Resource string Tool_Pencil.</summary>
    public static string Tool_Pencil => ResourceManager.GetString("Tool_Pencil", Culture) ?? "Tool_Pencil";

    /// <summary>Resource string Tool_Picker.</summary>
    public static string Tool_Picker => ResourceManager.GetString("Tool_Picker", Culture) ?? "Tool_Picker";

    /// <summary>Resource string Tool_Text.</summary>
    public static string Tool_Text => ResourceManager.GetString("Tool_Text", Culture) ?? "Tool_Text";

    /// <summary>Resource string Untitled.</summary>
    public static string Untitled => ResourceManager.GetString("Untitled", Culture) ?? "Untitled";

    /// <summary>Resource string View_FullScreen.</summary>
    public static string View_FullScreen => ResourceManager.GetString("View_FullScreen", Culture) ?? "View_FullScreen";

    /// <summary>Resource string View_Gridlines.</summary>
    public static string View_Gridlines => ResourceManager.GetString("View_Gridlines", Culture) ?? "View_Gridlines";

    /// <summary>Resource string View_Layers.</summary>
    public static string View_Layers => ResourceManager.GetString("View_Layers", Culture) ?? "View_Layers";

    /// <summary>Resource string View_Rulers.</summary>
    public static string View_Rulers => ResourceManager.GetString("View_Rulers", Culture) ?? "View_Rulers";

    /// <summary>Resource string View_StatusBar.</summary>
    public static string View_StatusBar => ResourceManager.GetString("View_StatusBar", Culture) ?? "View_StatusBar";

    /// <summary>Resource string View_Theme.</summary>
    public static string View_Theme => ResourceManager.GetString("View_Theme", Culture) ?? "View_Theme";

    /// <summary>Resource string View_Thumbnail.</summary>
    public static string View_Thumbnail => ResourceManager.GetString("View_Thumbnail", Culture) ?? "View_Thumbnail";

    /// <summary>Resource string View_Zoom.</summary>
    public static string View_Zoom => ResourceManager.GetString("View_Zoom", Culture) ?? "View_Zoom";

    /// <summary>Resource string View_Zoom100.</summary>
    public static string View_Zoom100 => ResourceManager.GetString("View_Zoom100", Culture) ?? "View_Zoom100";

    /// <summary>Resource string View_ZoomFit.</summary>
    public static string View_ZoomFit => ResourceManager.GetString("View_ZoomFit", Culture) ?? "View_ZoomFit";

    /// <summary>Resource string View_ZoomIn.</summary>
    public static string View_ZoomIn => ResourceManager.GetString("View_ZoomIn", Culture) ?? "View_ZoomIn";

    /// <summary>Resource string View_ZoomOut.</summary>
    public static string View_ZoomOut => ResourceManager.GetString("View_ZoomOut", Culture) ?? "View_ZoomOut";

    /// <summary>Resource string Yes.</summary>
    public static string Yes => ResourceManager.GetString("Yes", Culture) ?? "Yes";
}
