# Regenerates src/WinPaint.App/Resources/Strings.resx from Strings.txt (key=value per line, # comments).
# Strings.resx is the resource the app uses; Strings.txt is just a convenient editing format.
$ErrorActionPreference = "Stop"
$root = Split-Path $PSScriptRoot -Parent
$src = Join-Path $root "src/WinPaint.App/Resources/Strings.txt"
$dst = Join-Path $root "src/WinPaint.App/Resources/Strings.resx"
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('<?xml version="1.0" encoding="utf-8"?>')
[void]$sb.AppendLine('<root>')
[void]$sb.AppendLine('  <resheader name="resmimetype"><value>text/microsoft-resx</value></resheader>')
[void]$sb.AppendLine('  <resheader name="version"><value>2.0</value></resheader>')
[void]$sb.AppendLine('  <resheader name="reader"><value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>')
[void]$sb.AppendLine('  <resheader name="writer"><value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value></resheader>')
$seen = @{}
foreach ($line in [System.IO.File]::ReadAllLines($src, [System.Text.Encoding]::UTF8)) {
    if ($line.Trim() -eq "" -or $line.TrimStart().StartsWith("#")) { continue }
    $i = $line.IndexOf("=")
    $key = $line.Substring(0, $i).Trim()
    $val = $line.Substring($i + 1).Replace("\n", "`n")
    if ($seen.ContainsKey($key)) { throw "Duplicate key $key" }
    $seen[$key] = $true
    $esc = [System.Security.SecurityElement]::Escape($val)
    [void]$sb.AppendLine("  <data name=""$key"" xml:space=""preserve""><value>$esc</value></data>")
}
[void]$sb.AppendLine('</root>')
[System.IO.File]::WriteAllText($dst, $sb.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Host "Wrote $($seen.Count) strings to $dst"

# Strongly typed accessor (generated, committed) so XAML {x:Static} and code can use Strings.Key.
$cs = New-Object System.Text.StringBuilder
[void]$cs.AppendLine("// <auto-generated>Generated by tools/gen-strings.ps1 from Strings.txt. Do not edit.</auto-generated>")
[void]$cs.AppendLine("#nullable enable")
[void]$cs.AppendLine("namespace WinPaint.App.Resources;")
[void]$cs.AppendLine("")
[void]$cs.AppendLine("/// <summary>Localizable user-facing strings (backed by Strings.resx).</summary>")
[void]$cs.AppendLine("public static class Strings")
[void]$cs.AppendLine("{")
[void]$cs.AppendLine("    /// <summary>Resource manager for Strings.resx.</summary>")
[void]$cs.AppendLine("    public static System.Resources.ResourceManager ResourceManager { get; } = new(""WinPaint.App.Resources.Strings"", typeof(Strings).Assembly);")
[void]$cs.AppendLine("")
[void]$cs.AppendLine("    /// <summary>Culture override (null = current UI culture).</summary>")
[void]$cs.AppendLine("    public static System.Globalization.CultureInfo? Culture { get; set; }")
foreach ($k in $seen.Keys | Sort-Object) {
    [void]$cs.AppendLine("")
    [void]$cs.AppendLine("    /// <summary>Resource string $k.</summary>")
    [void]$cs.AppendLine("    public static string $k => ResourceManager.GetString(""$k"", Culture) ?? ""$k"";")
}
[void]$cs.AppendLine("}")
$csPath = Join-Path $root "src/WinPaint.App/Resources/Strings.cs"
[System.IO.File]::WriteAllText($csPath, $cs.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Host "Wrote $csPath"
